# Generated by Django 6.0.6 on 2026-07-21 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blogs_comme_post_id_782610_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='blogs_comme_post_id_f57867_idx'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
    ]
