# Generated by Django 6.0.6 on 2026-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_comment_blogs_comme_post_id_782610_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_verified',
        ),
    ]
