# Generated by Django 6.0.6 on 2026-07-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/profile_pictures/')),
                ('document', models.FileField(blank=True, null=True, upload_to='authors/docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='blogs.author')),
            ],
        ),
    ]
